site_name: JSL - JSON Serializable Language
site_description: A Network-Native Functional Programming Language
site_url: https://queelius.github.io/jsl

theme:
  name: material
  palette:
    primary: deep-purple
    accent: purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
    - Getting Started: getting-started.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Examples: getting-started/examples.md
  - Language Guide:
    - Syntax: language/syntax.md
    - AST: language/ast.md
    - Special Forms: language/special-forms.md
    - Templates: language/templates.md
    - Prelude: language/prelude.md
  - Tutorials:
    - First Program: tutorials/first-program.md
    - Functions: tutorials/functions.md
    - Data: tutorials/data.md
  - Host Interaction:
    - JHIP Protocol: jhip/protocol.md
    - Commands: jhip/commands.md
    - Custom Commands: jhip/custom.md
  - Architecture:
    - Philosophy: architecture/philosophy.md
    - Runtime: architecture/runtime.md
    - Security: architecture/security.md
    - Network Transparency: architecture/network.md
    - Serialization Design: architecture/serialization.md
    - Distributed Computing: architecture/distributed.md
  - Examples:
    - Simple: examples/simple.md
    - Practical: examples/practical.md
    - Advanced: examples/advanced.md
  - API Reference:
    - Serialization API: api/serialization.md
    - Runner: api/runner.md
    - Service: api/service.md

plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         options:
  #           show_root_heading: yes
  #           show_source: yes
  #           docstring_style: google
  #           merge_init_into_class: yes

markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
