site_name: JSL - JSON Serializable Language
site_description: A Network-Native Functional Programming Language
site_url: https://queelius.github.io/jsl

theme:
  name: material
  palette:
    primary: deep-purple
    accent: purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Language Guide:
    - Overview: language/overview.md
    - Syntax and Semantics: language/semantics.md
    - Environments: language/environments.md
    - Special Forms: language/special-forms.md
    - Objects: language/objects.md
    - Prelude: language/prelude.md
  - Tutorials:
    - First Program: tutorials/first-program.md
    - Functions: tutorials/functions.md
    - Data: tutorials/data.md
  - Host Interaction:
    - JHIP Protocol: jhip/protocol.md
    - Host Commands: jhip/host-commands.md
  - Architecture:
    - Philosophy: architecture/philosophy.md
    - Runtime: architecture/runtime.md
    - Security: architecture/security.md
    - Network Transparency: architecture/network.md
    - Serialization Design: architecture/serialization.md
    - Distributed Computing: architecture/distributed.md
  - Examples:
    - Simple: examples/simple.md
    - Practical: examples/practical.md
    - Advanced: examples/advanced.md
  - API Reference:
    - Core: api/core.md
    - Evaluator: api/evaluator.md
    - Serialization: api/serialization.md
    - Runner: api/runner.md
    - Fluent API: api/fluent.md

plugins:
  - search
  - with-pdf:
      # Generates a PDF version of the documentation
      # The output will be saved in the 'site/pdf' directory
      output_dir: pdf
      output_file: docs.pdf
      # Additional options for PDF generation
      latex:
        documentclass: article
        papersize: a4
        fontsize: 12pt
        geometry: margin=1in
      # add metadata: author is Alex Towell, email is lex@metafunctor
      metadata:
        author: Alex Towell
        email: lex@metafunctor
      # additional metadata
      additional:
        keywords: [JSL, documentation, PDF]
      title: JSL Documentation
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: yes
            show_source: yes
            docstring_style: google
            merge_init_into_class: yes

markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
